version: '3.2'
services:
  task-store:
    image: "samply/blaze:0.17"
    environment:
      BASE_URL: "http://localhost:8083"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      LOG_LEVEL: "debug"
    ports:
    - "8083:8080"
    volumes:
    - "task-store-data:/app/data"
  data-store:
    image: "samply/blaze:pr-768"
    environment:
      BASE_URL: "http://localhost:8084"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      LOG_LEVEL: "debug"
    ports:
    - "8084:8080"
    volumes:
    - "data-store-data:/app/data"
volumes:
  task-store-data:
  data-store-data:
