app:
  beam:
    appId: "app1.proxy1.broker"
    secret: App1Secret
    #appId: "report-hub.alex.broker.dev.ccp-it.dktk.dkfz.de"
    #secret: "3128937asd7823hZ."
    proxy:
      baseUrl: 'http://localhost:8081'
  taskStore:
    baseUrl: 'http://localhost:8083/fhir'
  dataStore:
    baseUrl: 'http://localhost:8084/fhir'
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
