app:
  beam:
    appId: ${PROXY_ID}
    secret: ${SECRET}
    proxy:
      baseUrl: ${BEAM_PROXY}
  taskStore:
    baseUrl: ${TASK_STORE}
  dataStore:
    baseUrl: ${LDM_URL}
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
