version: '3.2'
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    command:
    - --entrypoints.web.address=:80
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --api.dashboard=true
    - --accesslog=true
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.dashboard.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
    - "traefik.http.routers.dashboard.tls=false"
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  task-store:
    image: "samply/blaze:0.18"
    container_name: bridgehead-task-store
    environment:
      CONTEXT_PATH: "/task-store"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      LOG_LEVEL: "debug"
    volumes:
    - "task-store-data:/app/data"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.task_store.rule=PathPrefix(`/task-store`)"
    - "traefik.http.services.task_store.loadbalancer.server.port=8080"
  data-store:
    image: "samply/blaze:0.18"
    container_name: data-store
    environment:
      CONTEXT_PATH: "/data-store"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      LOG_LEVEL: "debug"
    volumes:
    - "data-store-data:/app/data"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.data_store.rule=PathPrefix(`/data-store`)"
    - "traefik.http.services.data_store.loadbalancer.server.port=8080"
  report-hub:
    image: "samply/report-hub:latest"
    container_name: report-hub
    environment:
      SPRING_WEBFLUX_BASE_PATH: "/report-hub"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      LOG_LEVEL: "debug"
      PROXY_ID: ${Proxy_ID}
      SECRET: ${SECRET}
      APP_TASKSTORE_BASEURL: "http://task-store:8080/task-store"
      APP_DATASTORE_BASEURL: "http://data-store:8080/data-store"
      BEAM_PROXY: "http://host.docker.internal:8081"
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.report-hub.rule=PathPrefix(`/report-hub`)"
    - "traefik.http.services.report-hub.loadbalancer.server.port=8080"
    depends_on:
    - task-store
    - data-store
volumes:
  task-store-data:
  data-store-data:
