name: Build

on:
  push:
    branches:
    - main
    - develop
    tags:
    - '*.*.*'
  pull_request:
    branches:
    - main
    - develop
  schedule:
  - cron: '0 1 * * *'

jobs:
  build-jar:
    uses: samply/github-workflows/.github/workflows/maven.yml@main
    with:
      publish: false
      java-version: 17
      artifact-name: "report-hub.jar"
      maven-command-line-parameters: "-DskipTests"
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Pwd
      run: pwd

  build-image:
    needs:
    - build-jar
    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
    with:
      image-name: 'samply/report-hub'
      artifact-name: 'report-hub.jar'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
